# Site settings
title: CyberGreen data inventory
short_title: Data inventory
description: |
    CyberGreen data inventory
baseurl: ""
url:  # the base hostname & protocol for your site
github_username:  cybergreen-net
github_repo:  inventory.cybergreen.net
paypal:
media: /img/medialibrary/

google_analytics: UA-80458846-1

markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: pretty

supporters:
  -
    name: UK-FCO-Logo.png
    footer_logo: /img/medialibrary/UK-FCO-Logo.png
    url: aaaa
  -
    name: jpcert_logo.gif
    footer_logo: /img/medialibrary/jpcert_logo.gif
    url: aaaa

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
