# Site settings
title: CyberGreen data inventory
short_title: Data inventory
description: |
    CyberGreen data inventory
baseurl: ""
url:  # the base hostname & protocol for your site
github_username:  cybergreen-net
github_repo:  inventory.cybergreen.net
paypal: 

devs:
  -
      name: Sam Smith
      github: mintcanary

contributors:
  -
      name: Rufus Pollock
      link: http://rufuspollock.org/

supporters:

google_analytics: UA-80458846-1

markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
