# Site settings
title: CyberGreen data inventory
short_title: Data inventory
description: |
    CyberGreen data inventory
baseurl: ""
url:  # the base hostname & protocol for your site
github_username:  cybergreen-net
github_repo:  inventory.cybergreen.net
paypal:
media: /img/medialibrary/

google_analytics: UA-80341493-1

markdown: kramdown

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

permalink: pretty

supporters:
  -
    name: UK-FCO-Logo.png
    footer_logo: /img/medialibrary/UK-FCO-Logo.png
    url: https://www.gov.uk/government/organisations/foreign-commonwealth-office
  -
    name: jpcert_logo.png
    footer_logo: /img/medialibrary/jpcert_logo.png
    url: https://www.jpcert.or.jp/english/
  -
    name: csa-logo.jpg
    footer_logo: /img/medialibrary/csa-logo.jpg
    url: https://www.csa.gov.sg

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
